import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { dashboardKey, getDashboard } from '../../shared/api/dashboard'
import { QueryState, StatusBadge } from '../../shared/components/WorkflowUi'
import type { CoverageMetric } from '../../shared/types/dashboard'
import { formatDate } from '../../shared/workflowFormat'

const labels: Record<string,string> = { implementation_coverage:'Implementation Coverage', decision_coverage:'Decision Coverage', conformance_among_decisive_checks:'Conformance Among Decisive Checks' }
const readable=(value:string)=>value.replaceAll('_',' ')
function Coverage({name,metric}:{name:string;metric:CoverageMetric|undefined}) { const assessed=metric?.status==='assessed'&&metric.denominator>0; return <article className="coverage-card"><span>{labels[name]}</span><strong>{assessed?`${metric.percentage}%`:'Not assessed'}</strong><small>{metric?`${metric.numerator} of ${metric.denominator}`:'No persisted measurement'}</small>{assessed&&<div className="distribution-track"><i style={{width:`${Math.min(100,metric.percentage??0)}%`}}/></div>}</article> }
function Distribution({title,values}:{title:string;values:Record<string,number>}) { const entries=Object.entries(values).sort((a,b)=>b[1]-a[1]); const max=Math.max(1,...entries.map(([,count])=>count)); return <article className="panel distribution-panel"><h3>{title}</h3>{entries.length===0?<p className="quiet-state">No persisted data</p>:entries.map(([name,count])=><div className="distribution-row" key={name}><span>{readable(name)}</span><div className="distribution-track"><i style={{width:`${count/max*100}%`}}/></div><strong>{count}</strong></div>)}</article> }

export function DashboardPage() {
  const query=useQuery({queryKey:dashboardKey,queryFn:getDashboard})
  return <section className="page-stack"><header className="page-heading heading-actions"><div><span className="eyebrow">Fleet posture</span><h1>Security operations dashboard</h1><p>Persisted audit truth across your organization, without recalculation.</p></div><Link className="button-primary" to="/audits">New Audit</Link></header><QueryState pending={query.isPending} error={query.error}>{query.data&&<><div className="metric-grid dashboard-metrics"><article><span>Total devices</span><strong>{query.data.total_devices}</strong><small>Known fleet</small></article><article><span>Audited</span><strong>{query.data.audited_devices}</strong><small>Completed audit truth</small></article><article><span>Unaudited</span><strong>{query.data.unaudited_devices}</strong><small>Awaiting completed audit</small></article><article className="risk-critical"><span>Critical risk</span><strong>{query.data.critical_risk_devices}</strong><small>Critical FAIL present</small></article><article className="risk-high"><span>High risk</span><strong>{query.data.high_risk_devices}</strong><small>High FAIL, excluding critical</small></article><article><span>Needs review</span><strong>{query.data.devices_needing_review}</strong><small>Unknown, manual, or process error</small></article></div><section><div className="section-title"><div><span className="eyebrow">Measured posture</span><h2>Coverage</h2></div></div><div className="coverage-grid">{Object.keys(labels).map(name=><Coverage key={name} name={name} metric={query.data.coverage[name]}/>)}</div></section><section><div className="section-title"><h2>Fleet distributions</h2></div><div className="dashboard-grid"><Distribution title="Verdicts" values={query.data.verdict_distribution}/><Distribution title="Severity" values={query.data.severity_distribution}/><Distribution title="Latest audit status" values={query.data.audit_status_distribution}/><Distribution title="Vendor" values={query.data.vendor_distribution}/><Distribution title="Profiles" values={query.data.profile_distribution}/><Distribution title="Device family" values={query.data.device_family_distribution}/></div></section><section className="panel"><div className="section-title"><div><span className="eyebrow">Newest first</span><h2>Recent audits</h2></div></div>{query.data.recent_audits.length===0?<p className="quiet-state">No audits have been created yet.</p>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Device</th><th>Status</th><th>Completed</th><th>Fail</th><th>Unknown</th><th>Critical / High</th></tr></thead><tbody>{query.data.recent_audits.map(audit=><tr key={audit.audit_id}><td><Link className="text-link" to={`/audits/${audit.audit_id}`}>{audit.device_name}</Link></td><td><StatusBadge value={audit.status}/></td><td>{formatDate(audit.completed_at)}</td><td>{audit.fail_count}</td><td>{audit.unknown_count}</td><td>{audit.critical_count} / {audit.high_count}</td></tr>)}</tbody></table></div>}</section></>}</QueryState></section>
}
