import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'

import { findingKeys, listFindings } from '../../shared/api/findings'
import { QueryState } from '../../shared/components/WorkflowUi'
import { ScopeSummary, SeverityBadge, VerdictBadge } from './FindingUi'

const pageSize = 25
export function FindingsPage() {
  const [params, setParams] = useSearchParams()
  const auditId = params.get('audit') ?? ''
  const filters = { verdict: params.get('verdict') ?? '', severity: params.get('severity') ?? '', security_domain: params.get('security_domain') ?? '', offset: Number(params.get('offset') ?? 0), limit: pageSize }
  const findings = useQuery({ queryKey: findingKeys.list(auditId, filters), queryFn: () => listFindings(auditId, filters), enabled: Boolean(auditId) })
  const update = (name: string, value: string) => setParams((current) => { const next = new URLSearchParams(current); if (value) next.set(name, value); else next.delete(name); next.delete('offset'); return next })
  const clear = () => setParams(auditId ? { audit: auditId } : {})
  if (!auditId) return <section className="page-stack"><header className="page-heading"><div><span className="eyebrow">Audit results</span><h1>Findings</h1></div></header><p className="quiet-state">Open an Audit and select its persisted findings to review results.</p></section>
  const hasFilters = Boolean(filters.verdict || filters.severity || filters.security_domain)
  return <section className="page-stack"><header className="page-heading"><div><span className="eyebrow">Audit results</span><h1>Findings</h1><p>Persisted compliance results for this audit. Results remain available while audit processing is recorded as in progress.</p></div></header><section className="panel finding-filters" aria-label="Findings filters"><label>Verdict<select value={filters.verdict} onChange={(event) => update('verdict', event.target.value)}><option value="">All verdicts</option><option value="pass">Pass</option><option value="fail">Fail</option><option value="unknown">Unknown</option><option value="manual_review">Manual review</option><option value="not_applicable">Not applicable</option><option value="process_error">Process error</option></select></label><label>Severity<select value={filters.severity} onChange={(event) => update('severity', event.target.value)}><option value="">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option><option value="informational">Informational</option></select></label><label>Security domain<input value={filters.security_domain} onChange={(event) => update('security_domain', event.target.value)} placeholder="For example, management" /></label>{hasFilters && <button className="button-quiet" onClick={clear}>Clear filters</button>}</section><QueryState pending={findings.isPending} error={findings.error} empty={findings.data?.total === 0 ? (hasFilters ? 'No findings match the selected filters.' : 'No findings are available for this audit.') : undefined}><>{findings.data && <><div className="finding-list">{findings.data.items.map((finding) => <Link className="finding-card" key={finding.finding_id} to={`/findings/${finding.finding_id}`}><div className="finding-card-head"><div><span className="eyebrow">{finding.security_domain}</span><h2>{finding.title}</h2></div><div className="badge-pair"><SeverityBadge value={finding.severity} /><VerdictBadge value={finding.verdict} /></div></div><p>{finding.explanation}</p><div className="finding-card-foot"><span><strong>Scope:</strong> <ScopeSummary scope={finding.affected_scope} /></span><small>{finding.rule_id}</small></div></Link>)}</div><nav className="pagination" aria-label="Findings pagination"><button className="button-secondary" disabled={filters.offset === 0} onClick={() => update('offset', String(Math.max(0, filters.offset - pageSize)))}>Previous</button><span>{filters.offset + 1}–{Math.min(filters.offset + pageSize, findings.data.total)} of {findings.data.total}</span><button className="button-secondary" disabled={filters.offset + pageSize >= findings.data.total} onClick={() => update('offset', String(filters.offset + pageSize))}>Next</button></nav></>}</></QueryState></section>
}
