import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'

import { findingKeys, getFinding, getFindingEvidence } from '../../shared/api/findings'
import { QueryState } from '../../shared/components/WorkflowUi'
import { formatDate, shortId } from '../../shared/workflowFormat'
import { ScopeSummary, SeverityBadge, StructuredValue, VerdictBadge } from './FindingUi'
import { readable } from './findingFormat'
import { RemediationPanel } from './RemediationPanel'

export function FindingDetailPage() {
  const { findingId = '' } = useParams()
  const finding = useQuery({ queryKey: findingKeys.detail(findingId), queryFn: () => getFinding(findingId), enabled: Boolean(findingId) })
  const evidence = useQuery({ queryKey: findingKeys.evidence(findingId), queryFn: () => getFindingEvidence(findingId), enabled: Boolean(findingId) })
  return <section className="page-stack"><Link className="back-link" to={finding.data ? `/audits/${finding.data.audit_id}/findings` : '/findings'}>Back to findings</Link><QueryState pending={finding.isPending} error={finding.error}>{finding.data && <><header className="page-heading"><div><span className="eyebrow">{finding.data.security_domain}</span><h1>{finding.data.title}</h1><p>{finding.data.explanation}</p></div><div className="badge-pair"><SeverityBadge value={finding.data.severity} /><VerdictBadge value={finding.data.verdict} /></div></header>{finding.data.verdict === 'unknown' && finding.data.unknown_reason ? <aside className="boundary-note"><strong>Result is unknown</strong><span>Reason: {readable(finding.data.unknown_reason)}</span></aside> : null}<section className="result-grid"><article className="panel"><span className="eyebrow">Observed state</span><StructuredValue value={finding.data.observed_state} /></article><article className="panel"><span className="eyebrow">Expected state</span><StructuredValue value={finding.data.expected_state} /></article></section><section className="panel"><h2>Affected scope</h2><ScopeSummary scope={finding.data.affected_scope} /></section>{finding.data.framework_references.length > 0 ? <section className="panel"><h2>Mapped controls</h2><p className="quiet-state">Technical evidence mapped to selected framework controls.</p><ul>{finding.data.framework_references.map((reference, index) => <li key={`${String(reference.control_id)}-${index}`}>{String(reference.framework)} {String(reference.revision)}: {String(reference.control_id)} - {String(reference.control_title)}</li>)}</ul></section> : null}<EvidenceSection pending={evidence.isPending} error={evidence.error} data={evidence.data} /><RemediationPanel findingId={finding.data.finding_id} /><details className="panel provenance-details"><summary>Rule provenance</summary><dl className="detail-grid"><div><dt>Rule ID</dt><dd>{finding.data.rule_id}</dd></div><div><dt>Rule pack version</dt><dd>{shortId(finding.data.rule_pack_version_id)}</dd></div><div><dt>Finding ID</dt><dd>{finding.data.finding_id}</dd></div><div><dt>Created</dt><dd>{formatDate(finding.data.created_at)}</dd></div></dl></details></>}</QueryState></section>
}

function EvidenceSection({ pending, error, data }: { pending: boolean; error: unknown; data: ReturnType<typeof getFindingEvidence> extends Promise<infer T> ? T | undefined : never }) {
  if (pending) return <p className="quiet-state">Loading persisted evidence...</p>
  if (error) return <p className="error-message" role="alert">Evidence could not be resolved safely for this finding.</p>
  if (!data || data.status === 'no_evidence') return <section className="panel"><h2>Evidence</h2><p>No concrete source evidence is available for this finding.</p></section>
  return <section className="page-stack"><h2>Evidence</h2>{data.states.map((state) => <article className="panel evidence-state" key={state.effective_state_id}><div className="section-title"><div><span className="eyebrow">Effective state</span><h3>{state.field_id}</h3></div><span className="finding-badge">{readable(state.resolution_status)}</span></div><dl className="detail-grid"><div><dt>Value</dt><dd><StructuredValue value={state.effective_value} /></dd></div><div><dt>Scope</dt><dd><ScopeSummary scope={state.scope} /></dd></div>{state.unresolved_reason ? <div><dt>Reason</dt><dd>{readable(state.unresolved_reason)}</dd></div> : null}</dl>{state.facts.map((fact) => <section className="evidence-fact" key={fact.fact_id}><h4>{fact.field_id}</h4>{fact.artifacts.map((artifact, index) => <div className="evidence-artifact" key={`${artifact.artifact_id}-${index}`}><strong>{artifact.original_filename}</strong>{artifact.available && artifact.excerpt !== null ? <pre className="evidence-excerpt">{artifact.excerpt}</pre> : <p className="quiet-state">The referenced evidence excerpt is unavailable.</p>}</div>)}</section>)}</article>)}</section>
}
