#config-version=FGT v7.4.3
config system interface
    edit "port1"
        set allowaccess telnet https ssh
    next
end
config system global
    set admintimeout 10
    set admin-https-ssl-versions tlsv1-2 tlsv1-3
end
config log syslogd setting
    set server "192.0.2.10"
end
config ntpserver
    edit 1
        set server "192.0.2.20"
    next
end
