"""Seed B10 reviewed multi-vendor remediation guidance."""
from datetime import datetime, timezone
from alembic import op
import sqlalchemy as sa
revision="20260909_0018"; down_revision="20260909_0017"; branch_labels=depends_on=None
T=sa.table("remediation_procedures",sa.column("procedure_id",sa.Uuid()),sa.column("procedure_key",sa.String()),sa.column("version",sa.Integer()),sa.column("previous_procedure_id",sa.Uuid()),sa.column("rule_id",sa.String()),sa.column("title",sa.String()),sa.column("security_objective",sa.String()),sa.column("description",sa.String()),sa.column("status",sa.String()),sa.column("profile_applicability",sa.JSON()),sa.column("prerequisites",sa.JSON()),sa.column("safety_warnings",sa.JSON()),sa.column("required_parameters",sa.JSON()),sa.column("configuration_context",sa.JSON()),sa.column("ordered_steps",sa.JSON()),sa.column("verification_steps",sa.JSON()),sa.column("rollback_steps",sa.JSON()),sa.column("validation_results",sa.JSON()),sa.column("source_references",sa.JSON()),sa.column("created_at",sa.DateTime(timezone=True)),sa.column("schema_version",sa.String()))
P={"cisco":["cisco.ios_xe.17@1.0.0"],"fortios":["fortinet.fortios.7@1.0.0"],"junos":["juniper.junos.18@1.0.0"]}; W="Guidance preview only; no device connection or execution occurs."
S={"cisco":{"title":"Cisco IOS XE 17 Line Commands","url":"https://www.cisco.com/c/en/us/td/docs/routers/sdwan/configuration/command/cisco-sd-wan-qualified-command-reference-guide/line-commands.html"},"fortios":{"title":"FortiOS 7 config system interface/global","url":"https://docs.fortinet.com/document/fortigate/7.0.0/cli-reference"},"junos":{"title":"Junos system services and idle-timeout","url":"https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/idle-timeout-edit-system-login.html"}}
ROWS=[("20000000-0000-0000-0000-000000000001","cisco.ssh-only-vty","cisco","management.telnet.disabled","Cisco SSH-only VTY management",[{"name":"vty_range","type":"enum","values":["0 4","5 15","0 15"],"required":True}], ["line vty {vty_range}","transport input ssh"],"show running-config | section line vty","Restore captured prior transport configuration through change control."),("20000000-0000-0000-0000-000000000002","cisco.vty-idle-timeout","cisco","management.idle_timeout.maximum", "Cisco VTY idle timeout",[{"name":"vty_range","type":"enum","values":["0 4","5 15","0 15"],"required":True},{"name":"minutes","type":"integer","minimum":1,"maximum":60,"required":True}], ["line vty {vty_range}","exec-timeout {minutes} 0"],"show running-config | section line vty","Restore captured prior timeout; zero is not emitted."),("20000000-0000-0000-0000-000000000003","fortios.secure-interface-access","fortios","management.remote.telnet.enabled","FortiOS secure management interface access",[{"name":"interface","type":"hostname","required":True},{"name":"protocols","type":"enum","values":["https ssh","https ping ssh","ping ssh"],"required":True}], ["config system interface","edit {interface}","set allowaccess {protocols}","next","end"],"show system interface {interface}","Restore captured prior allowaccess protocol set."),("20000000-0000-0000-0000-000000000004","fortios.admin-timeout","fortios","management.idle_timeout.maximum","FortiOS administrator idle timeout",[{"name":"minutes","type":"integer","minimum":1,"maximum":480,"required":True}], ["config system global","set admintimeout {minutes}","end"],"show system global | grep admintimeout","Restore captured prior admintimeout."),("20000000-0000-0000-0000-000000000005","junos.ssh-only-service","junos","management.remote.telnet.enabled","Junos SSH-only management service",[],["set system services ssh","delete system services telnet"],"show configuration system services","Restore captured previous SSH/Telnet service state."),("20000000-0000-0000-0000-000000000006","junos.login-idle-timeout","junos","management.idle_timeout.maximum","Junos system login idle timeout",[{"name":"minutes","type":"integer","minimum":1,"maximum":60,"required":True}],["set system login idle-timeout {minutes}"],"show configuration system login","Restore captured prior timeout; custom login classes can override global behavior.")]
def row(x):
 i,k,v,r,t,params,steps,verify,rollback=x
 return {"procedure_id":i,"procedure_key":k,"version":1,"previous_procedure_id":None,"rule_id":r,"title":t,"security_objective":t,"description":"Reviewed bounded guidance.","status":"PUBLISHED","profile_applicability":{"profile_version_ids":P[v]},"prerequisites":[{"text":"Capture current configuration and maintain alternate access."}],"safety_warnings":[W],"required_parameters":params,"configuration_context":[],"ordered_steps":[{"text":z} for z in steps],"verification_steps":[{"text":verify}],"rollback_steps":[{"text":rollback}],"validation_results":[{"review":"passed","parameter_validation":True}],"source_references":[{"vendor":v,"accessed_at":"2026-09-09",**S[v]}],"created_at":datetime.now(timezone.utc),"schema_version":"1.0.0"}
def upgrade():
 op.bulk_insert(T,[row(x) for x in ROWS])
 op.execute("""CREATE FUNCTION protect_published_remediation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN ('PUBLISHED','SUPERSEDED','published','superseded') THEN RAISE EXCEPTION 'published remediation is immutable'; END IF; RETURN NEW; END $$""")
 op.execute("CREATE TRIGGER trg_remediation_published_immutable BEFORE UPDATE OR DELETE ON remediation_procedures FOR EACH ROW EXECUTE FUNCTION protect_published_remediation()")
def downgrade():
 op.execute("DROP TRIGGER IF EXISTS trg_remediation_published_immutable ON remediation_procedures")
 op.execute("DROP FUNCTION IF EXISTS protect_published_remediation()")
 op.execute(sa.delete(T).where(T.c.procedure_id.in_([x[0] for x in ROWS])))
